# Generated by Django 2.2.8 on 2020-01-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='audio',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word',
            field=models.CharField(max_length=255),
        ),
    ]
