# Generated by Django 2.2.8 on 2020-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0002_auto_20200123_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='word',
            new_name='word1',
        ),
        migrations.AddField(
            model_name='document',
            name='word2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='word3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
