# Generated by Django 3.1 on 2020-08-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0005_auto_20200825_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativeword',
            old_name='word',
            new_name='alt_word',
        ),
    ]
