# Generated by Django 3.2.16 on 2023-02-18 14:17

from django.db import migrations, models
import lunes_cms.cms.models.static


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_document_created_by_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='name')),
                ('icon', models.ImageField(blank=True, upload_to=lunes_cms.cms.models.static.upload_sponsor_icons, verbose_name='icon')),
            ],
        ),
    ]
