# Generated by Django 3.2.15 on 2022-09-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_alter_document_word_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="word_type",
            field=models.CharField(
                choices=[(0, "Nomen"), (1, "Verb"), (2, "Adjektiv")],
                default=0,
                max_length=255,
                verbose_name="word type",
            ),
        ),
    ]
