# Generated by Django 3.1.1 on 2020-11-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20201102_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingset',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='alternativeword',
            name='article',
            field=models.CharField(choices=[('der', 'der'), ('das', 'das'), ('die', 'die'), ('die (Plural)', 'die (Plural)')], default='', max_length=255),
        ),
    ]
