# Generated by Django 3.2.16 on 2023-03-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_sponsor"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="plural",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="plural"
            ),
        ),
    ]
