# Generated by Django 3.2.16 on 2023-03-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0009_sponsor"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("username", models.CharField(default="", max_length=30, unique=True)),
                ("email", models.EmailField(default="", max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
