# Generated by Django 3.2.16 on 2023-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0010_add_plural_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="job_title_feminin_plural",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="feminin plural"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_title_feminin_singluar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="feminin singluar"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_title_masculin_plural",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="masculin plural"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_title_masculin_singluar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="masculin singluar"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_title_neutrum_plural",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="neutrum plural"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="job_title_neutrum_singluar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="neutrum singluar"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="word_type",
            field=models.CharField(
                choices=[
                    ("Nomen", "Substantiv"),
                    ("Verb", "Verb"),
                    ("Adjektiv", "Adjektiv"),
                    ("Numeral", "Numeral"),
                    ("Pronomen", "Pronomen"),
                    ("Adverb", "Adverb"),
                    ("Personenbezeichnung", "Personenbezeichnung"),
                ],
                default="",
                max_length=255,
                verbose_name="word type",
            ),
        ),
    ]
