# Generated by Django 3.2.21 on 2024-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration file to add a new field sponsor to discipline
    """

    dependencies = [
        ("cms", "0011_document_example_sentence"),
    ]

    operations = [
        migrations.AddField(
            model_name="discipline",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipline",
                to="cms.sponsor",
                verbose_name="sponsor",
            ),
        ),
    ]
