# Generated by Django 3.2rc1 on 2021-04-13 15:07

from django.db import migrations, models
import vocgui.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0014_auto_20210406_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[vocgui.validators.validate_file_extension, vocgui.validators.validate_file_size]),
        ),
    ]
