# Generated by Django 3.2.21 on 2024-05-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add genus field
    """

    dependencies = [
        ("cms", "0014_add_plural_field_and_plural_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="alternativeword",
            name="grammatical_gender",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "kein"),
                    (1, "Maskulinum"),
                    (2, "Femininum"),
                    (3, "Neutrum"),
                    (4, "Plural"),
                ],
                null=True,
                verbose_name="grammatical gender",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="grammatical_gender",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, "kein"),
                    (1, "Maskulinum"),
                    (2, "Femininum"),
                    (3, "Neutrum"),
                    (4, "Plural"),
                ],
                null=True,
                verbose_name="Grammatical gender",
            ),
        ),
    ]
