# Generated by Django 3.2.21 on 2024-11-23 08:50

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration file to change the verbose names of model trainingset
    """

    dependencies = [
        ("cms", "0015_add_grammatical_gender_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingset",
            options={
                "verbose_name": "Training set",
                "verbose_name_plural": "Training sets",
            },
        ),
    ]
