# Generated by Django 3.2rc1 on 2021-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0015_alter_document_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
