# Generated by Django 3.2.21 on 2024-11-23 08:51

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration file to change the verbose names of model trainingset
    """

    dependencies = [
        ("cms", "0016_alter_trainingset_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainingset",
            options={
                "verbose_name": "training set",
                "verbose_name_plural": "training sets",
            },
        ),
    ]
