# Generated by Django 3.2.2 on 2021-05-13 14:45

from django.db import migrations, models
import lunes_cms.cms.validators


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_documentimage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativeword',
            options={'verbose_name': 'alternative word', 'verbose_name_plural': 'alternative words'},
        ),
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'discipline', 'verbose_name_plural': 'disciplines'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'vocabulary', 'verbose_name_plural': 'vocabulary'},
        ),
        migrations.AlterModelOptions(
            name='documentimage',
            options={'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='trainingset',
            options={'verbose_name': 'training set', 'verbose_name_plural': 'training sets'},
        ),
        migrations.AlterField(
            model_name='alternativeword',
            name='alt_word',
            field=models.CharField(max_length=255, verbose_name='alternative word'),
        ),
        migrations.AlterField(
            model_name='alternativeword',
            name='article',
            field=models.CharField(choices=[('keiner', 'keiner'), ('der', 'der'), ('das', 'das'), ('die', 'die'), ('die (Plural)', 'die (Plural)')], default='', max_length=255, verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=255, verbose_name='discipline'),
        ),
        migrations.AlterField(
            model_name='document',
            name='article',
            field=models.CharField(choices=[('keiner', 'keiner'), ('der', 'der'), ('das', 'das'), ('die', 'die'), ('die (Plural)', 'die (Plural)')], default='', max_length=255, verbose_name='article'),
        ),
        migrations.AlterField(
            model_name='document',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', validators=[lunes_cms.cms.validators.validate_file_extension, lunes_cms.cms.validators.validate_file_size, lunes_cms.cms.validators.validate_multiple_extensions], verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word',
            field=models.CharField(max_length=255, verbose_name='word'),
        ),
        migrations.AlterField(
            model_name='document',
            name='word_type',
            field=models.CharField(choices=[('Nomen', 'Nomen'), ('Verb', 'Verb'), ('Adjektiv', 'Adjektiv')], default='', max_length=255, verbose_name='word type'),
        ),
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to='images/', validators=[lunes_cms.cms.validators.validate_multiple_extensions]),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='title',
            field=models.CharField(max_length=255, verbose_name='training set'),
        ),
    ]
