# Generated by Django 3.2rc1 on 2021-05-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_auto_20210513_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='released',
            field=models.BooleanField(default=False, verbose_name='released'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='released',
            field=models.BooleanField(default=False, verbose_name='released'),
        ),
    ]
