# Generated by Django 3.2rc1 on 2021-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0018_auto_20210522_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('order',), 'verbose_name': 'discipline', 'verbose_name_plural': 'disciplines'},
        ),
        migrations.AlterModelOptions(
            name='trainingset',
            options={'ordering': ('order',), 'verbose_name': 'training set', 'verbose_name_plural': 'training sets'},
        ),
        migrations.AddField(
            model_name='discipline',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingset',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
