# Generated by Django 3.2rc1 on 2021-05-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20210523_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
