# Generated by Django 3.2.2 on 2021-06-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_merge_0021_auto_20210611_0641_0022_auto_20210612_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativeword',
            name='plural_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='plural_article',
            field=models.BooleanField(default=False),
        ),
    ]
