# Generated by Django 3.2.4 on 2021-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20210617_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimage',
            name='confirmed',
            field=models.BooleanField(default=True, verbose_name='confirmed'),
        ),
    ]
