# Generated by Django 3.2.2 on 2021-06-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0024_auto_20210617_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternativeword',
            name='plural_article',
        ),
        migrations.RemoveField(
            model_name='document',
            name='plural_article',
        ),
    ]
