# Generated by Django 3.2.7 on 2021-09-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cms', '0030_alter_discipline_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='auth.group', verbose_name='created by'),
        ),
    ]
