# Generated by Django 3.2.7 on 2021-10-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0033_groupapikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupapikey',
            options={'verbose_name': 'API Key', 'verbose_name_plural': 'API Keys'},
        ),
    ]
