# Generated by Django 3.2.7 on 2021-12-04 10:00

from django.db import migrations, models
import django.db.models.deletion
from mptt import register, managers, fields


def rebuild_tree(apps, schema_editor):
    """
    Rebuild mptt tree after creating necessary fields. The default of all ordering
    fields is generally set to 0. In order to make mptt work it is necessary
    to run TrainingSet.objects.rebuild() before running the server.
    """
    training_set_model = apps.get_model("vocgui", "TrainingSet")
    manager = managers.TreeManager()
    manager.model = training_set_model
    register(training_set_model)
    manager.contribute_to_class(training_set_model, "objects")
    manager.rebuild()

class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0034_alter_groupapikey_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingset',
            options={'verbose_name': 'training set', 'verbose_name_plural': 'training sets'},
        ),
        migrations.RemoveField(
            model_name='trainingset',
            name='order',
        ),
        migrations.AddField(
            model_name='trainingset',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingset',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingset',
            name='parent',
            field=fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='vocgui.trainingset', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingset',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(
          rebuild_tree
        ),
    ]
