# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "django-jazzmin"
        # Pinned to 3.0.1 due to compatibility issues with newer versions
