changelog:
  exclude:
    labels:
      - exclude-changelog
  categories:
    - title: Features, Fixes & Enhancements 🎉
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
          - maintenance
    - title: Dependencies 📦
      labels:
        - dependencies
    - title: Maintenance 🛠
      labels:
        - maintenance
