repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: [--external-sources]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: translations
        name: translations
        description: Check if the translation file is up-to-date
        entry: tools/check_translations.sh
        language: script
        pass_filenames: false
