site_name: Lunes CMS – Benutzerhandbuch
site_description: Benutzerhandbuch für das Lunes Content Management System
site_url: https://digitalfabrik.github.io/lunes-cms/
docs_dir: user_docs
site_dir: user_docs_site

theme:
  name: material
  language: de
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.sections
    - navigation.top
    - content.action.view

nav:
  - Startseite: index.md
  - Anmelden: login.md
  - Passwort zurücksetzen: password_reset.md
  - Benutzer:innen:
    - Benutzer:in anlegen: add_user.md
    - Benutzer:in bearbeiten (Informationen): edit_user_information.md
    - Benutzer:in bearbeiten (Berechtigungen): edit_user_permissions.md
    - Benutzer:in löschen: delete_user.md
  - Gruppen:
    - Gruppe anlegen: add_group.md
    - Gruppe bearbeiten: edit_group.md
    - Gruppe löschen: delete_group.md
  - Jobs:
    - Job hinzufügen: add_job.md
    - Job bearbeiten: edit_job.md
    - Job löschen: delete_job.md
    - Mehrere Jobs löschen: bulk_delete_jobs.md
  - Einheiten:
    - Einheit hinzufügen: add_unit.md
    - Einheit bearbeiten: edit_unit.md
    - Einheit löschen: delete_unit.md
    - Mehrere Einheiten löschen: bulk_delete_units.md
  - Wörter:
    - Wort hinzufügen: add_word.md
    - Wort-Audio und -Bild generieren: generate_word_audio_and_image.md
    - Wort bearbeiten: edit_word.md
    - Wort löschen: delete_word.md
    - Mehrere Wörter löschen: bulk_delete_words.md

markdown_extensions:
  - pymdownx.magiclink
