description: Send a notification (to Mattermost) at the end of a job, based on success or failure. Must be the last step in a job.
parameters:
  success_message:
    default: ''
    type: string
  failure_mentions:
    default: '@leandra.hahn @johannes.stock @sascha.beele @david.venhoff @andreas.fischer'
    type: string
  success_mentions:
    default: ''
    type: string
  allow_all_branches:
    default: false
    type: boolean
  channel:
    default: lunes-app-notifications
    type: string
steps:
  - run:
      command: |
        echo 'export MM_MESSAGE=":fire: [${CIRCLE_JOB}](${CIRCLE_BUILD_URL}) failed on branch ${CIRCLE_BRANCH}! :fire: << parameters.failure_mentions >>"' >> $BASH_ENV
      name: Mattermost - Prepare failure message
      when: on_fail
  - run:
      command: echo 'export MM_MESSAGE="<< parameters.success_message >>"' >> $BASH_ENV
      name: Mattermost - Prepare success message
      when: on_success
  - run:
      name: Mattermost Status Alert
      when: always
      command: |
        CHANNEL="<< parameters.channel >>"
        ALLOW_ALL_BRANCHES=<< parameters.allow_all_branches >>

        begins_with() { case $1 in "$2"*) true;; *) false;; esac; }

        echo $MM_MESSAGE

        if ! ($ALLOW_ALL_BRANCHES || [ "$CIRCLE_BRANCH" = "main" ] || begins_with $CIRCLE_BRANCH "release" || begins_with $CIRCLE_BRANCH "hotfix"); then
          echo "Not on main or release branch. Skipping."
          exit 0
        fi

        if [ -z "$MM_MESSAGE" ]; then
          echo "No message set. Skipping."
          exit 0
        fi

        if [ -z "${MM_WEBHOOK}" ]; then
          echo "No mattermost webhook set. Skipping."
          exit 0
        fi

        STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" -X POST -H 'Content-type: application/json' \
          --data "{\"channel\": \"$CHANNEL\", \"username\": \"circleci\", \"text\": \"$MM_MESSAGE\"}" \
          "${MM_WEBHOOK}")

        if [ "$STATUS" -ne "200" ]; then
          echo "Notification not sent. Status: $STATUS"
          exit 1
        fi

        echo "Notification sent!"
