when:
  or:
    - equal: [<< pipeline.parameters.run_commit_develop >>, "run"]
    - and:
        - equal: [<< pipeline.parameters.run_commit_develop >>, "run_if_on_develop"]
        - equal: [develop, << pipeline.git.branch >>]
jobs:
  - install
  - compile-translations:
      requires:
        - install
  - e2e:
      requires:
        - compile-translations
  - bump-dev-version:
      requires:
        - install
  - build-package:
      name: build-dev-package
      requires:
        - bump-dev-version
        - e2e
  - publish-package:
      name: publish-dev-package
      context: pypi-test
      requires:
        - build-dev-package
