when:
  and:
    - << pipeline.parameters.run_main >>
    - equal: [main, << pipeline.git.branch >>]
jobs:
  - install:
      name: install-main
      filters:
        branches:
          only: main
  - bump-version:
      context: deliverino
      requires:
        - install-main
