when:
  and:
    - << pipeline.parameters.run_promotion >>
    - or:
        - equal: [main, << pipeline.git.branch >>]
        - matches:
            pattern: "^(release|hotfix)-.*"
            value: << pipeline.git.branch >>
jobs:
  - publish-release-artifact:
      context: pypi
  - promote-release:
      context: deliverino
      requires:
        - publish-release-artifact
