version: 2.1

parameters:
  run_commit:
    default: true
    type: boolean
  run_commit_develop:
    default: "run_if_on_develop"
    type: enum
    enum: ["run_if_on_develop", "run", "skip"]
  run_main:
    default: false
    type: boolean
  run_deploy:
    default: false
    type: boolean

executors:
  python:
    docker:
      - image: cimg/python:3.11
