version: 2.1

jobs:
  install:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - run:
          name: Installing system dependencies
          command: sudo apt-get update && cat requirements.system | xargs sudo apt-get install
      - restore_cache:
          key: pip-{{ checksum "setup.cfg" }}-v1
      - run:
          name: Creating virtual environment
          command: |
            if [[ -d ".venv" ]]; then
              echo "Virtual environment restored from cache, skipping pip install"
            else
              python3 -m venv .venv
              source .venv/bin/activate
              pip install -e .[dev,doc]
            fi
      - save_cache:
          key: pip-{{ checksum "setup.cfg" }}-v1
          paths:
            - .venv
            - lunes_cms.egg-info
            - /home/circleci/.cache/pip
      - persist_to_workspace:
          root: .
          paths:
            - .venv
            - lunes_cms.egg-info
  test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run migrations and tests
          command: |
            source .venv/bin/activate
            lunes-cms-cli migrate
            lunes-cms-cli test lunes_cms
          environment:
            LUNES_CMS_SECRET_KEY: circleci-dummy-key
      - store_artifacts:
          path: test-reports/
          destination: python_app
  black:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          source .venv/bin/activate
          black --check .
  build-documentation:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
          source .venv/bin/activate
          dev-tools/build_documentation.sh

workflows:
  develop:
    jobs:
      - install
      - test:
          requires:
            - install
      - black:
          requires:
            - install
      - build-documentation:
          requires:
            - install
