# Generated by Django 5.2.15 on 2026-07-23 16:27

from django.db import migrations


class Migration(migrations.Migration):
    """
    Create the DuplicatedVocabulary proxy of Word — no new table, just an
    admin entry that groups under its own "Analyse" sidebar section (#531).
    """

    initial = True

    dependencies = [
        ("cmsv2", "0026_index_word_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuplicatedVocabulary",
            fields=[],
            options={
                "verbose_name": "Duplicated vocabulary",
                "verbose_name_plural": "Duplicated vocabulary",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cmsv2.word",),
        ),
    ]
