# Generated by Django 5.2.15 on 2026-08-11 14:13

from django.db import migrations


class Migration(migrations.Migration):
    """
    Create the AcceptedDuplicates proxy of AcceptedWordDuplicate — no new
    table, just an admin entry under the "Analyse" sidebar section, next to
    the renamed "Open duplicates" entry.
    """

    dependencies = [
        ("analysis", "0001_initial"),
        ("cmsv2", "0031_accepted_word_duplicate"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedDuplicates",
            fields=[],
            options={
                "verbose_name": "Accepted duplicates",
                "verbose_name_plural": "Accepted duplicates",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("cmsv2.acceptedwordduplicate",),
        ),
        migrations.AlterModelOptions(
            name="duplicatedvocabulary",
            options={
                "verbose_name": "Open duplicates",
                "verbose_name_plural": "Open duplicates",
            },
        ),
    ]
