# Generated by Django 5.2.15 on 2026-08-11 14:55

from django.db import migrations


class Migration(migrations.Migration):
    """
    Add the ``can_view_duplicates`` permission, gating both "Open
    duplicates" and "Accepted duplicates" (issue #531). Assign it to
    whichever groups should see the duplicate-vocabulary pages via the
    admin's own Group permissions widget - not hard-coded here.
    """

    dependencies = [
        ("analysis", "0002_accepted_duplicates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="duplicatedvocabulary",
            options={
                "permissions": [
                    ("can_view_duplicates", "Can view and manage duplicates")
                ],
                "verbose_name": "Open duplicates",
                "verbose_name_plural": "Open duplicates",
            },
        ),
    ]
