docker:
  - image: cimg/node:lts
steps:
  - checkout
  - restore_cache:
      key: npm-{{ checksum "package.json" }}-v1
  - run:
      name: Install npm dependencies
      command: npm install
  - save_cache:
      key: npm-{{ checksum "package.json" }}-v1
      paths:
        - node_modules
  - run:
      name: Build TypeScript
      command: npm run build
  - persist_to_workspace:
      root: .
      paths:
        - lunes_cms/static/js
  - notify
