executor: python
steps:
  - checkout
  - attach_workspace:
      at: .
  - restore-environment-variables
  - activate-venv
  - run:
      name: Build lunes-cms package
      command: |
        export SETUPTOOLS_SCM_PRETEND_VERSION="${NEW_VERSION}"
        pip install .
        python -m build --sdist .
        python -m build --wheel .
  - persist_to_workspace:
      root: .
      paths:
        - dist
  - notify
