docker:
  - image: cimg/node:lts
steps:
  - checkout
  - run:
      name: Install app-toolbelt
      command: npm ci
  - run:
      name: Calculate next version
      command: |
        NEW_VERSION=$(npx --no app-toolbelt v0 version calc | jq -r .versionName)
        echo "export NEW_VERSION=$NEW_VERSION" >> $BASH_ENV
  - run:
      name: Bump git version
      command: |
        HOTFIX_FLAG=$([[ "${CIRCLE_BRANCH}" == hotfix* ]] && echo "--hotfix" || true)
        npx --no app-toolbelt v0 release bump-to "${NEW_VERSION}" \
          --private-key "${DELIVERINO_PRIVATE_KEY}" \
          --owner "${CIRCLE_PROJECT_USERNAME}" \
          --repo "${CIRCLE_PROJECT_REPONAME}" \
          --branch "${CIRCLE_BRANCH}" \
          ${HOTFIX_FLAG}
  - persist-environment-variables
  - notify:
      allow_all_branches: true
