docker:
  - image: cimg/python:3.11
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Install translation requirements
      command: sudo apt-get update && sudo apt-get install gettext pcregrep
  - run:
      name: Check translation file for missing or empty entries
      command: ./tools/check_translations.sh
