executor: python
steps:
  - checkout
  - attach_workspace:
      at: .
  - run:
      name: Install gettext
      command: sudo apt-get update && sudo apt-get install gettext
  - run:
      name: Compile translation file
      command: |
        source .venv/bin/activate
        cd lunes_cms
        lunes-cms-cli compilemessages
      environment:
        LUNES_CMS_SECRET_KEY: circleci-dummy-key
  - persist_to_workspace:
      root: .
      paths:
        - lunes_cms/locale/de/LC_MESSAGES/django.mo
        - lunes_cms/locale/de/LC_MESSAGES/djangojs.mo
