docker:
  - image: cimg/node:lts
steps:
  - checkout
  - attach_workspace:
      at: .
  - restore-environment-variables
  - run:
      name: Install app-toolbelt
      command: npm ci
  - run:
      name: Create GitHub pre-release
      command: |
        HOTFIX_FLAG=$([[ "${CIRCLE_BRANCH}" == hotfix* ]] && echo "--hotfix --branch ${CIRCLE_BRANCH}" || true)
        RELEASE=$(npx --no app-toolbelt v0 release create all "${NEW_VERSION}" \
          --private-key "${DELIVERINO_PRIVATE_KEY}" \
          --owner "${CIRCLE_PROJECT_USERNAME}" \
          --repo "${CIRCLE_PROJECT_REPONAME}" \
          ${HOTFIX_FLAG})
        echo "export RELEASE_ID=$(echo ${RELEASE} | jq .id)" >> ${BASH_ENV}
        echo "export RELEASE_NOTES=$(echo ${RELEASE} | jq .releaseNotes)" >> ${BASH_ENV}
  - run:
      name: Upload package to GitHub release
      command: |
        npx --no app-toolbelt v0 release upload \
          --releaseId "${RELEASE_ID}" \
          --files "$(ls dist/lunes_cms-*.tar.gz)" \
          --private-key "${DELIVERINO_PRIVATE_KEY}" \
          --owner "${CIRCLE_PROJECT_USERNAME}" \
          --repo "${CIRCLE_PROJECT_REPONAME}"
  - run:
      name: Generate SBOM
      command: |
        npx --no app-toolbelt v0 generate sbom \
          --version-name "${NEW_VERSION}" \
          --release-id "${RELEASE_ID}" \
          --path lunes_cms/_manifest/spdx_2.2/manifest.spdx.json \
          --branch "${CIRCLE_BRANCH}" \
          --private-key "${DELIVERINO_PRIVATE_KEY}" \
          --owner "${CIRCLE_PROJECT_USERNAME}" \
          --repo "${CIRCLE_PROJECT_REPONAME}"
  - run:
      name: Notify mattermost about pre-release
      command: |
        MESSAGE="##### Lunes CMS version [${NEW_VERSION}](https://github.com/digitalfabrik/lunes-cms/releases/tag/${NEW_VERSION}) beta has been released successfully :tada:\n${RELEASE_NOTES}\nhttps://github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases/tag/${NEW_VERSION}"
        npx --no app-toolbelt v0 notify mattermost \
          --message "${MESSAGE}" \
          --channel releases \
          --allow-all-branches
  - notify:
      allow_all_branches: true
