executor: python
steps:
  - checkout
  - attach_workspace:
      at: .
  - install-uv
  - run:
      name: Install e2e dependencies
      command: uv sync --extra dev --extra e2e --locked
  - activate-venv
  - configure-deliverino
  - run:
      name: Deploy user manual to GitHub Pages
      command: mkdocs gh-deploy --remote-branch gh-pages-user-docs
  - notify
