executor: python
steps:
  - checkout
  - install-uv
  - restore_cache:
      key: uv-{{ checksum "uv.lock" }}-v1
  - sync-venv
  - save_cache:
      key: uv-{{ checksum "uv.lock" }}-v1
      paths:
        - .venv
        - /home/circleci/.cache/uv
  - persist_to_workspace:
      root: .
      paths:
        - .venv
  - notify
