executor: python
resource_class: small
steps:
  - checkout
  - attach_workspace:
      at: .
  - activate-venv
  - run:
      name: Check isort code style
      command: isort . --skip-glob "**/migrations/**"
  - notify
