docker:
  - image: cimg/python:3.13.13
    environment:
      LUNES_CMS_SECRET_KEY: circleci-dummy-key
      LUNES_CMS_DB_BACKEND: sqlite
steps:
  - checkout
  - restore_cache:
      key: pip-3.13.13-{{ checksum "pyproject.toml" }}-v1
  - run:
      name: Create virtual environment
      command: |
        if [[ -d ".venv" ]]; then
          echo "Virtual environment restored from cache, skipping pip install"
        else
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -e .[dev,pinned,dev-pinned]
        fi
  - save_cache:
      key: pip-3.13.13-{{ checksum "pyproject.toml" }}-v1
      paths:
        - .venv
        - lunes_cms.egg-info
        - /home/circleci/.cache/pip
  - run:
      name: Migrate database
      command: |
        source .venv/bin/activate
        lunes-cms-cli migrate
  - run:
      name: Load basic test data
      command: |
        source .venv/bin/activate
        lunes-cms-cli loaddata lunes_cms/cms/fixtures/test_data.json
  - run:
      name: Run tests
      command: |
        source .venv/bin/activate
        ./tools/test.sh --ci
