# Generated by Django 5.2.11 on 2026-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to limit choices for the analytics event type to `job_selected`
    """

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[("job_selected", "Job Selected")],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
