# Generated by Django 5.2.11 on 2026-03-11 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the JobSelectionAggregate model
    """

    dependencies = [
        ("analytics", "0002_alter_analyticsevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSelectionAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.IntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                ("selection_count", models.IntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job_id", "date"), name="unique_job_selection_per_day"
                    )
                ],
            },
        ),
    ]
