# Generated by Django 5.2.11 on 2026-03-16 18:06

from django.db import migrations


class Migration(migrations.Migration):
    """
    Removes an index on the analytics event which was already mostly covered
    """

    dependencies = [
        ("analytics", "0003_jobselectionaggregate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="analytics_a_install_354de4_idx",
        ),
    ]
