# Generated by Django 5.2.12 on 2026-03-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds duration tracking models and event types.
    """

    dependencies = [
        ("analytics", "0003_jobselectionaggregate"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="analyticsevent",
            name="analytics_a_install_354de4_idx",
        ),
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job_selected", "Job Selected"),
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("module_duration", "Module Duration"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="SessionAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("duration_buckets", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ModuleDurationAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("exercise_type", models.IntegerField()),
                ("unit_id", models.IntegerField()),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "exercise_type", "unit_id"),
                        name="unique_module_duration_key",
                    )
                ],
            },
        ),
    ]
