# Generated by Django 5.2.12

from django.db import migrations, models

from lunes_cms.analytics.models.analytics_event import AnalyticsEvent


class Migration(migrations.Migration):
    """
    Adds exercise dropout tracking model and event type.
    """

    dependencies = [
        ("analytics", "0004_add_duration_tracking_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job_selected", "Job Selected"),
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("module_duration", "Module Duration"),
                    ("exercise_dropout", "Exercise Dropout"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="DropoutAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=AnalyticsEvent.ExerciseType.choices,
                        max_length=50,
                    ),
                ),
                ("unit_id", models.IntegerField(null=True)),
                ("dropout_position", models.IntegerField()),
                ("total_items", models.IntegerField()),
                ("dropout_count", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "date",
                            "exercise_type",
                            "unit_id",
                            "dropout_position",
                            "total_items",
                        ),
                        name="unique_dropout_key",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
