# Generated by Django 5.2.11 on 2026-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the session and module event types"""

    dependencies = [
        ("analytics", "0004_remove_analyticsevent_analytics_a_install_354de4_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job_selected", "Job Selected"),
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("module_duration", "Module Duration"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
    ]
