# Generated by Django 5.2.10 on 2026-04-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add exercise_repetition event type and create ExerciseRepetitionAggregate model.
    """

    dependencies = [
        ("analytics", "0005_add_dropout_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job_selected", "Job Selected"),
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("module_duration", "Module Duration"),
                    ("exercise_dropout", "Exercise Dropout"),
                    ("exercise_repetition", "Exercise Repetition"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="moduledurationaggregate",
            name="exercise_type",
            field=models.CharField(
                choices=[("word_list", "Word List"), ("word_choice", "Word Choice")],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ExerciseRepetitionAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.IntegerField()),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("word_list", "Word List"),
                            ("word_choice", "Word Choice"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(max_length=32)),
                ("repetition_count", models.PositiveIntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit_id", "exercise_type", "session_id"),
                        name="unique_exercise_repetition_per_session",
                    )
                ],
            },
        ),
    ]
