# Generated by Django 5.2.12 on 2026-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ExerciseRepetitionAggregate model"""

    dependencies = [
        ("analytics", "0005_add_dropout_tracking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("job_selected", "Job Selected"),
                    ("session_start", "Session Start"),
                    ("session_end", "Session End"),
                    ("module_duration", "Module Duration"),
                    ("exercise_dropout", "Exercise Dropout"),
                    ("exercise_repetition", "Exercise Repetition"),
                ],
                db_index=True,
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ExerciseRepetitionAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_id", models.IntegerField(db_index=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("vocabulary_list", "Vocabulary List"),
                            ("word_choice", "Word Choice"),
                            ("article_choice", "Article Choice"),
                            ("write", "Write"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("repetition_count", models.IntegerField()),
                ("date", models.DateField(db_index=True)),
                ("start_count", models.IntegerField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit_id", "exercise_type", "date"),
                        name="unique_exercise_repetition_per_session",
                    )
                ],
            },
        ),
    ]
