# Generated by Django 5.2.12 on 2026-03-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the SessionAggregate model"""

    dependencies = [
        ("analytics", "0005_alter_analyticsevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("duration_buckets", models.JSONField(default=dict)),
            ],
        ),
    ]
