# Generated by Django 5.2.12 on 2026-03-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adds the ModuleDurationAggregate model"""

    dependencies = [
        ("analytics", "0006_sessionaggregate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleDurationAggregate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("exercise_type", models.IntegerField()),
                ("unit_id", models.IntegerField()),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "exercise_type", "unit_id"),
                        name="unique_module_duration_key",
                    )
                ],
            },
        ),
    ]
