# Generated by Django 5.2.12 on 2026-05-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Generally adds training exercises to tracking:
    - adds job_id to ModuleDurationAggregate, DropoutAggregate, and ExerciseRepetitionAggregate
    - makes unit_id nullable on DropoutAggregate and ExerciseRepetitionAggregate
    - adds vocabulary_item_id to DropoutAggregate
    """

    dependencies = [
        ("analytics", "0006_alter_analyticsevent_event_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dropoutaggregate",
            name="unique_dropout_key",
        ),
        migrations.RemoveConstraint(
            model_name="exerciserepetitionaggregate",
            name="unique_exercise_repetition_per_session",
        ),
        migrations.RemoveConstraint(
            model_name="moduledurationaggregate",
            name="unique_module_duration_key",
        ),
        migrations.AddField(
            model_name="dropoutaggregate",
            name="job_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="dropoutaggregate",
            name="vocabulary_item_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="exerciserepetitionaggregate",
            name="job_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="moduledurationaggregate",
            name="job_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="exerciserepetitionaggregate",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("word_list", "Word List"),
                    ("word_choice", "Word Choice"),
                    ("image", "Image Training"),
                    ("sentence", "Sentence Training"),
                    ("speech", "Speech Training"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="exerciserepetitionaggregate",
            name="unit_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="moduledurationaggregate",
            name="exercise_type",
            field=models.CharField(
                choices=[
                    ("word_list", "Word List"),
                    ("word_choice", "Word Choice"),
                    ("image", "Image Training"),
                    ("sentence", "Sentence Training"),
                    ("speech", "Speech Training"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="moduledurationaggregate",
            name="unit_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddConstraint(
            model_name="dropoutaggregate",
            constraint=models.UniqueConstraint(
                fields=(
                    "date",
                    "exercise_type",
                    "unit_id",
                    "job_id",
                    "vocabulary_item_id",
                    "dropout_position",
                    "total_items",
                ),
                name="unique_dropout_key",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="exerciserepetitionaggregate",
            constraint=models.UniqueConstraint(
                fields=("unit_id", "job_id", "exercise_type", "session_id"),
                name="unique_exercise_repetition_per_session",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="moduledurationaggregate",
            constraint=models.UniqueConstraint(
                fields=("date", "exercise_type", "unit_id", "job_id"),
                name="unique_module_duration_key",
                nulls_distinct=False,
            ),
        ),
    ]
