# Generated by Django 5.2.12 on 2026-05-13 11:27

from django.db import migrations


class Migration(migrations.Migration):
    """Add the ``SessionDurationReport`` proxy model that surfaces the Total Session Duration report in the admin sidebar."""

    dependencies = [
        ("analytics", "0007_keep_raw_events_drop_buckets"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionDurationReport",
            fields=[],
            options={
                "verbose_name": "Total Session Duration",
                "verbose_name_plural": "Total Session Duration",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("analytics.sessionaggregate",),
        ),
    ]
