# Generated by Django 5.2.17 on 2026-10-07 15:13

from django.db import migrations


class Migration(migrations.Migration):
    """
    Drop the obsolete aggregate tables; daily summaries are pushed to InfluxDB.
    """

    dependencies = [
        ("analytics", "0008_keep_raw_events_drop_buckets"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DropoutAggregate",
        ),
        migrations.DeleteModel(
            name="ExerciseRepetitionAggregate",
        ),
        migrations.DeleteModel(
            name="JobSelectionAggregate",
        ),
        migrations.DeleteModel(
            name="ModuleDurationAggregate",
        ),
        migrations.DeleteModel(
            name="SessionAggregate",
        ),
    ]
