# Generated by Django 5.1.2 on 2025-05-23 11:01

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to set verbose names for Job, Unit, and Word models.

    This migration configures the verbose_name and verbose_name_plural attributes
    for the Job, Unit, and Word models to improve admin interface display.
    """

    dependencies = [
        ("cmsv2", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={"verbose_name": "Job", "verbose_name_plural": "Jobs"},
        ),
        migrations.AlterModelOptions(
            name="unit",
            options={"verbose_name": "Unit", "verbose_name_plural": "Units"},
        ),
        migrations.AlterModelOptions(
            name="word",
            options={"verbose_name": "Word", "verbose_name_plural": "Words"},
        ),
    ]
