# Generated by Django 5.1.2 on 2025-05-23 15:22

from django.db import migrations, models
import lunes_cms.cmsv2.models.static


class Migration(migrations.Migration):
    """
    Migration to add an image field to the Word model.

    This migration adds an ImageField to the Word model for storing word images.
    """

    dependencies = [
        ("cmsv2", "0005_alter_job_icon_alter_unit_icon_alter_word_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to=lunes_cms.cmsv2.models.static.convert_umlaute_images,
                verbose_name="image",
            ),
        ),
    ]
