# Generated by Django 5.1.2 on 2025-05-24 10:00

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to remove the direct 'words' field from the Unit model.
    """

    dependencies = [
        ("cmsv2", "0006_word_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="words",
        ),
    ]
