# Generated by Django 5.1.2 on 2025-05-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to modify the audio_check_status field in the Word model.

    This migration changes the audio_check_status field to allow null values,
    making it optional for words that don't have audio files.
    """

    dependencies = [
        ("cmsv2", "0009_word_audio_check_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="audio_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                max_length=20,
                null=True,
                verbose_name="audio check status",
            ),
        ),
    ]
