# Generated by Django 5.1.2 on 2025-06-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add image check status fields to UnitWordRelation and Word models.

    This migration adds image_check_status fields to both the UnitWordRelation and Word models
    to track the verification status of images.
    """

    dependencies = [
        ("cmsv2", "0010_alter_word_audio_check_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="image_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                max_length=20,
                null=True,
                verbose_name="image check status",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="image_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                max_length=20,
                null=True,
                verbose_name="image check status",
            ),
        ),
    ]
