# Generated by Django 5.1.2 on 2025-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to alter unitwordrelation image check status and more."""

    dependencies = [
        ("cmsv2", "0011_unitwordrelation_image_check_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitwordrelation",
            name="image_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                default="NOT_CHECKED",
                max_length=20,
                null=True,
                verbose_name="image check status",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="audio_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                default="NOT_CHECKED",
                max_length=20,
                null=True,
                verbose_name="audio check status",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="image_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                default="NOT_CHECKED",
                max_length=20,
                null=True,
                verbose_name="image check status",
            ),
        ),
    ]
