# Generated by Django 5.1.2 on 2025-10-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add v1_id field to Job, Unit, and Word models for API v1 compatibility tracking.
    """

    dependencies = [
        ("cmsv2", "0012_alter_unitwordrelation_image_check_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="v1_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="v1_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="word",
            name="v1_id",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
