# Generated by Django 5.1.2 on 2025-10-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add example_sentence field to UnitWordRelation model."""

    dependencies = [
        ("cmsv2", "0013_job_v1_id_unit_v1_id_word_v1_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="example_sentence",
            field=models.TextField(blank=True, verbose_name="example sentence"),
        ),
    ]
