# Generated by Django 5.1.2 on 2025-10-21 19:27

from django.db import migrations, models

import lunes_cms.cmsv2.models.static
import lunes_cms.cmsv2.validators


class Migration(migrations.Migration):
    """Add example_sentence_audio field to UnitWordRelation model."""

    dependencies = [
        ("cmsv2", "0015_word_example_sentence_audio"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="example_sentence_audio",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=lunes_cms.cmsv2.models.static.convert_umlaute_audio,
                validators=[
                    lunes_cms.cmsv2.validators.validate_file_extension,
                    lunes_cms.cmsv2.validators.validate_file_size,
                    lunes_cms.cmsv2.validators.validate_multiple_extensions,
                ],
                verbose_name="example sentence audio",
            ),
        ),
    ]
