# Generated by Django 5.1.2 on 2025-11-04 11:25

from django.db import migrations


class Migration(migrations.Migration):
    """Merge migrations from multiple branches."""

    dependencies = [
        ("cmsv2", "0014_feedback"),
        ("cmsv2", "0016_unitwordrelation_example_sentence_audio"),
    ]

    operations = []
