# Generated by Django 5.1.2 on 2025-11-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add example_sentence_check_status field to UnitWordRelation and Word models."""

    dependencies = [
        ("cmsv2", "0017_merge_20251104_1125"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="example_sentence_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                default="NOT_CHECKED",
                max_length=20,
                null=True,
                verbose_name="example sentence check status",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="example_sentence_check_status",
            field=models.CharField(
                choices=[("NOT_CHECKED", "Not Checked"), ("CONFIRMED", "Confirmed")],
                default="NOT_CHECKED",
                max_length=20,
                null=True,
                verbose_name="example sentence check status",
            ),
        ),
    ]
