# Generated by Django 5.1.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add example_sentence_audio_regenerated field to Word model."""

    dependencies = [
        ("cmsv2", "0018_unitwordrelation_example_sentence_check_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="example_sentence_audio_regenerated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the audio has been regenerated with the new TTS model.",
                verbose_name="example sentence audio regenerated",
            ),
        ),
    ]
