# Generated by Django 5.1.2 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add example_sentence_audio_regenerated field to UnitWordRelation model."""

    dependencies = [
        ("cmsv2", "0019_word_example_sentence_audio_regenerated"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="example_sentence_audio_regenerated",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the audio has been regenerated with the new TTS model.",
                verbose_name="example sentence audio regenerated",
            ),
        ),
    ]
