# Generated by Django 5.2.10 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsv2", "0020_unitwordrelation_example_sentence_audio_regenerated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="released",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="released"
            ),
        ),
    ]
