# Generated by Django 5.2.10 on 2026-05-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add a database index on the Unit.released field to speed up filtered queries.
    """

    dependencies = [
        ("cmsv2", "0022_alter_imagereview_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="released",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="released"
            ),
        ),
    ]
