# Generated by Django 5.2.14 on 2026-05-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add a status summary property to ImageReview for easier filtering of pending reviews.
    """

    dependencies = [
        ("cmsv2", "0023_alter_unit_released"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagereview",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW_WORD", "New Vocabulary"),
                    ("SUBMISSION_1", "1st Submission"),
                    ("SUBMISSION_2", "2nd Submission"),
                    ("SUBMISSION_3", "3rd Submission"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="NEW_WORD",
                max_length=20,
                verbose_name="status",
            ),
        ),
    ]
