# Generated by Django 5.2.15 on 2026-07-10 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add a created_by_user field to Job, Unit and Word to track the individual
    user who created them, alongside the existing owner group. Also change
    created_by's on_delete behavior from CASCADE to SET_NULL, so deleting a
    group no longer deletes all vocabulary it owns.
    """

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("cmsv2", "0024_refactor_check_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_jobs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_units",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="created_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_words",
                to=settings.AUTH_USER_MODEL,
                verbose_name="creator",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job",
                to="auth.group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="group",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                max_length=255,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.group",
                verbose_name="group",
            ),
        ),
    ]
