# Generated by Django 5.2.14 on 2026-07-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add the ``archived`` flag to the Job model so jobs can be
    archived instead of published (issue #890).
    """

    dependencies = [
        ("cmsv2", "0025_job_created_by_user_unit_created_by_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived jobs are hidden from the default job list and are not published via the API. They can be restored at any time.",
                verbose_name="archived",
            ),
        ),
    ]
