# Generated by Django 5.2.15 on 2026-07-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Index Word.word, queried heavily by duplicate-vocabulary detection (#531).
    """

    dependencies = [
        ("cmsv2", "0025_job_created_by_user_unit_created_by_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(db_index=True, max_length=255, verbose_name="word"),
        ),
    ]
