# Generated by Django 5.2.15 on 2026-07-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    """Track duplicate-vocabulary groups accepted as intentional (#531)."""

    dependencies = [
        ("cmsv2", "0026_index_word_word"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedWordDuplicate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        related_name="accepted_duplicate_groups",
                        to="cmsv2.word",
                        verbose_name="words",
                    ),
                ),
            ],
            options={
                "verbose_name": "accepted word duplicate",
                "verbose_name_plural": "accepted word duplicates",
            },
        ),
    ]
