# Generated by Django 5.2.12 on 2026-07-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Reintroduce alternative words from v1 as a new AlternativeWord model
    linked to Word and remove the unused definition and additional meaning
    fields from Word.
    """

    dependencies = [
        ("cmsv2", "0026_job_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="additional_meaning_1",
        ),
        migrations.RemoveField(
            model_name="word",
            name="additional_meaning_2",
        ),
        migrations.RemoveField(
            model_name="word",
            name="definition",
        ),
        migrations.CreateModel(
            name="AlternativeWord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alt_word",
                    models.CharField(max_length=255, verbose_name="alternative word"),
                ),
                (
                    "grammatical_gender",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "kein"),
                            (1, "Maskulinum"),
                            (2, "Femininum"),
                            (3, "Neutrum"),
                            (4, "Plural"),
                        ],
                        null=True,
                        verbose_name="Grammatical gender",
                    ),
                ),
                (
                    "singular_article",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "keiner"),
                            (1, "der"),
                            (2, "die"),
                            (3, "das"),
                            (4, "die (Plural)"),
                        ],
                        null=True,
                        verbose_name="singular article",
                    ),
                ),
                (
                    "plural",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="plural"
                    ),
                ),
                (
                    "plural_article",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "keiner"), (1, "die (Plural)")],
                        null=True,
                        verbose_name="plural article",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_words",
                        to="cmsv2.word",
                        verbose_name="word",
                    ),
                ),
            ],
            options={
                "verbose_name": "alternative word",
                "verbose_name_plural": "alternative words",
            },
        ),
    ]
