# Generated by Django 5.2.16 on 2026-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add optional pronunciation field to Word model."""

    dependencies = [
        ("cmsv2", "0027_remove_word_additional_meaning_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="pronunciation",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Only for loanwords that the speech synthesis mispronounces (e.g. 'Baiser'). Write how the word should sound, spelled out in German (e.g. 'Besee') - not phonetic notation! Leave empty otherwise.",
                max_length=255,
                verbose_name="pronunciation",
            ),
        ),
    ]
