# Generated by Django 5.2.16 on 2026-08-18 11:37

import django.db.models.deletion
import lunes_cms.cmsv2.models.static
import lunes_cms.cmsv2.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmsv2", "0029_backfill_null_check_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reviewassignment",
            name="unique_review_assignment",
        ),
        migrations.RemoveField(
            model_name="reviewassignment",
            name="assigned_by",
        ),
        migrations.RemoveField(
            model_name="reviewassignment",
            name="reviewer",
        ),
        migrations.RemoveField(
            model_name="reviewassignment",
            name="unit",
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proposed_audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=lunes_cms.cmsv2.models.static.convert_umlaute_audio,
                        validators=[
                            lunes_cms.cmsv2.validators.validate_file_extension,
                            lunes_cms.cmsv2.validators.validate_file_size,
                            lunes_cms.cmsv2.validators.validate_multiple_extensions,
                        ],
                        verbose_name="audio",
                    ),
                ),
                (
                    "proposed_image",
                    models.ImageField(
                        blank=True,
                        upload_to=lunes_cms.cmsv2.models.static.convert_umlaute_images,
                        verbose_name="image",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="assigned at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("CHANGE_REQUESTED", "Change requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANNOT_BE_ASSESSED", "Cannot be assessed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="review status",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_review_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned by",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewer",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_assignments",
                        to="cmsv2.word",
                        verbose_name="unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Review",
            },
        ),
        migrations.DeleteModel(
            name="ImageReview",
        ),
        migrations.DeleteModel(
            name="ReviewAssignment",
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("word", "reviewer"), name="unique_review_assignment"
            ),
        ),
    ]
