# Generated by Django 5.2.17 on 2026-09-08 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add the area model and the area of a job.
    """

    dependencies = [
        ("cmsv2", "0031_remove_alternative_word_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="area"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        help_text="These users manage the content of this area. They only see jobs, units and words of the areas they administer.",
                        related_name="administered_areas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="administrators",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area",
                "verbose_name_plural": "Areas",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="area",
            field=models.ForeignKey(
                blank=True,
                help_text="Jobs of an area are only visible to the administrators of that area. Jobs without an area belong to the main app.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="cmsv2.area",
                verbose_name="area",
            ),
        ),
    ]
