# Generated by Django 5.2.17 on 2026-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration allows the comment to be blank, so that it is not required in the form
    """

    dependencies = [
        ("cmsv2", "0032_review_unit_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="comment"
            ),
        ),
    ]
