# Generated by Django 5.2.17 on 2026-09-15 07:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add the codes of an area.
    """

    dependencies = [
        ("cmsv2", "0033_area_job_area"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="At least 8 characters, only digits and upper case letters allowed.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            django.core.validators.RegexValidator(
                                "^[0-9A-Z]*$",
                                "Only digits and upper case letters allowed",
                            ),
                        ],
                        verbose_name="code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="modified at"),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="cmsv2.area",
                        verbose_name="area",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area code",
                "verbose_name_plural": "Area codes",
                "ordering": ["code"],
            },
        ),
    ]
