# Generated by Django 5.2.17 on 2026-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds a review priority to the review model
    """

    dependencies = [
        ("cmsv2", "0033_alter_review_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_priority",
            field=models.IntegerField(default=0, verbose_name="review priority"),
        ),
    ]
