# Generated by Django 5.2.17 on 2026-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration applies some changes required for the reviewer view:
    - Makes the review comment blank
    - Adds a priority field to Review
    - Adds a new permission for reviews
    """

    dependencies = [
        ("cmsv2", "0035_areaaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="comment",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="comment"
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="review_priority",
            field=models.IntegerField(default=0, verbose_name="review priority"),
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "permissions": [("can_review", "Can review assigned reviews")],
                "verbose_name": "Review",
                "verbose_name_plural": "Review",
            },
        ),
    ]
