# Generated by Django 5.2.15 on 2026-09-18 13:37

from django.db import migrations, models

import lunes_cms.cmsv2.models.static
import lunes_cms.cmsv2.validators


class Migration(migrations.Migration):
    """
    Migration file to add the branding fields (logo, primary and secondary
    color, additional information) to the Area model.
    """

    dependencies = [
        ("cmsv2", "0035_areaaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Shown on landing page.",
                upload_to=lunes_cms.cmsv2.models.static.upload_area_logos,
                verbose_name="logo",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="primary_color",
            field=models.CharField(
                blank=True,
                help_text="A hex color e.g. #000000 for black.",
                max_length=7,
                validators=[lunes_cms.cmsv2.validators.validate_hex_color],
                verbose_name="primary color",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="secondary_color",
            field=models.CharField(
                blank=True,
                help_text="A hex color e.g. #000000 for black.",
                max_length=7,
                validators=[lunes_cms.cmsv2.validators.validate_hex_color],
                verbose_name="secondary color",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="additional_information",
            field=models.TextField(blank=True, verbose_name="additional information"),
        ),
        migrations.AddField(
            model_name="area",
            name="additional_information_url",
            field=models.URLField(
                blank=True, verbose_name="additional information URL"
            ),
        ),
    ]
