# Generated by Django 5.2.15 on 2026-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to add the ``is_main_app`` flag to the Area model.

    This marks the one area that stands for the main app catalog, see #1016.
    """

    dependencies = [
        ("cmsv2", "0036_area_branding"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="is_main_app",
            field=models.BooleanField(
                default=False,
                help_text="Marks the one area for the main app catalog",
                verbose_name="main app",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main_app", True)),
                fields=("is_main_app",),
                name="unique_main_app_area",
            ),
        ),
    ]
