# Generated by Django 5.2.15 on 2026-09-21 00:00

import django.db.models.deletion
from django.db import migrations, models

import lunes_cms.cmsv2.models.job


# pylint: disable=unused-argument
def create_main_app_area_and_migrate_jobs(apps, schema_editor):
    """
    Create the one area that stands for the main app catalog, and move every
    job that was not yet assigned an area into it.

    Main app content used to be represented by an empty ``Job.area``. From
    here on every job always has an area, and the one created below is the
    area that stands for the main app, see #1016.

    :param apps: The configuration of installed applications
    :type apps: ~django.apps.registry.Apps

    :param schema_editor: The database abstraction layer that creates actual SQL code
    :type schema_editor: ~django.db.backends.base.schema.BaseDatabaseSchemaEditor
    """
    Area = apps.get_model("cmsv2", "Area")
    Job = apps.get_model("cmsv2", "Job")
    main_app_area, _created = Area.objects.get_or_create(
        is_main_app=True,
        defaults={"name": "Lunes"},
    )
    Job.objects.filter(area__isnull=True).update(area=main_app_area)


# pylint: disable=unused-argument
def delete_main_app_area(apps, schema_editor):
    """
    Remove the main app area again, for reversing this migration.

    The jobs that were backfilled into it are pointed back to an empty area
    first, since the foreign key protects the area from deletion while
    anything still references it.

    :param apps: The configuration of installed applications
    :type apps: ~django.apps.registry.Apps

    :param schema_editor: The database abstraction layer that creates actual SQL code
    :type schema_editor: ~django.db.backends.base.schema.BaseDatabaseSchemaEditor
    """
    Area = apps.get_model("cmsv2", "Area")
    Job = apps.get_model("cmsv2", "Job")
    Job.objects.filter(area__is_main_app=True).update(area=None)
    Area.objects.filter(is_main_app=True).delete()


class Migration(migrations.Migration):
    """
    Migration file to create the main app area and make every job belong to
    an area, see #1016.
    """

    dependencies = [
        ("cmsv2", "0037_area_is_main_app"),
    ]

    operations = [
        migrations.RunPython(
            create_main_app_area_and_migrate_jobs, delete_main_app_area
        ),
        migrations.AlterField(
            model_name="job",
            name="area",
            field=models.ForeignKey(
                default=lunes_cms.cmsv2.models.job.default_area_id,
                help_text=(
                    "Jobs of an area are only visible to the administrators "
                    "of that area. Jobs of the main app catalog belong to "
                    "the 'Lunes' area."
                ),
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="cmsv2.area",
                verbose_name="area",
            ),
        ),
    ]
