# Generated by Django 5.2.17 on 2026-09-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds the new AIGeneration model
    """

    dependencies = [
        ("cmsv2", "0038_create_main_app_area_and_make_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation_event",
                    models.CharField(
                        choices=[
                            ("IMAGE", "Image"),
                            ("WORD_AUDIO", "Word audio"),
                            ("EXAMPLE_SENTENCE", "Example sentence"),
                            ("EXAMPLE_SENTENCE_AUDIO", "Example sentence audio"),
                        ],
                        max_length=32,
                        verbose_name="generation event",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The areas administered by the user who requested the generation, can be empty.",
                        related_name="ai_generations",
                        to="cmsv2.area",
                        verbose_name="areas",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI generation",
                "verbose_name_plural": "AI generations",
                "ordering": ["-created_at"],
            },
        ),
    ]
