# Generated by Django 5.2.17 on 2026-10-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add the ``expert_reviewed`` quality seal to the Job model
    (issue #762).
    """

    dependencies = [
        ("cmsv2", "0038_create_main_app_area_and_make_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="expert_reviewed",
            field=models.BooleanField(
                default=False,
                help_text="Whether external experts have approved the content of this job.",
                verbose_name="expert reviewed",
            ),
        ),
    ]
