# Generated by Django 5.2.17 on 2026-09-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration file to record where the image of a word or unit-word relation
    came from, and whether it carries the AI-disclosure label, see #936.
    """

    dependencies = [
        ("cmsv2", "0038_create_main_app_area_and_make_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitwordrelation",
            name="image_source",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("UPLOADED", "Uploaded"),
                    ("AI_UNLABELED", "AI-generated without label"),
                    ("AI_LABELED", "AI-generated with label"),
                    ("AI_MARKED", "AI-generated, labeled afterwards"),
                ],
                default="UNKNOWN",
                editable=False,
                max_length=20,
                verbose_name="image source",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="image_source",
            field=models.CharField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("UPLOADED", "Uploaded"),
                    ("AI_UNLABELED", "AI-generated without label"),
                    ("AI_LABELED", "AI-generated with label"),
                    ("AI_MARKED", "AI-generated, labeled afterwards"),
                ],
                default="UNKNOWN",
                editable=False,
                max_length=20,
                verbose_name="image source",
            ),
        ),
    ]
