from __future__ import annotations

from datetime import timedelta
from hashlib import sha256
from secrets import token_urlsafe

from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from .area import Area
from .area_code import AreaCode

#: The number of random bytes a token is made of. Base64 encoded, this results
#: in a token of 43 characters.
TOKEN_BYTES = 32

#: The number of leading characters of a token that are stored in the clear, so
#: that a token can be told apart from another one in the admin.
TOKEN_PREFIX_LENGTH = 8

#: How old ``last_used_at`` has to be before it is written again. Without this,
#: every single API request of every client would cause a write.
LAST_USED_RESOLUTION = timedelta(days=1)


def generate_token() -> str:
    """
    Generate a random access token.

    :return: A token that can be handed to a client
    """
    return token_urlsafe(TOKEN_BYTES)


def hash_token(token: str) -> str:
    """
    Hash an access token for storage and lookup.

    A plain hash without a salt is enough here: the token is generated by the
    server with full entropy, so it cannot be attacked with a dictionary, and
    the lookup has to work without knowing which row is meant.

    :param token: The token to hash
    :return: The hexadecimal SHA-256 digest of the token
    """
    return sha256(token.encode()).hexdigest()


class AreaAccessToken(models.Model):
    """
    Model representing the access of one client installation to an area.

    A client redeems an :class:`~lunes_cms.cmsv2.models.area_code.AreaCode` once
    and receives a token that does not expire. As long as that token is sent
    with a request, the API answers with the content of the area instead of the
    content of the main app.

    Only the hash of the token is stored: the token is handed out once at
    registration and never shown again, so there is no reason to keep the
    plaintext where a database dump could pick it up.
    """

    area = models.ForeignKey(
        Area,
        on_delete=models.CASCADE,
        related_name="access_tokens",
        verbose_name=_("area"),
    )
    code = models.ForeignKey(
        AreaCode,
        on_delete=models.CASCADE,
        related_name="access_tokens",
        verbose_name=_("code"),
        help_text=_(
            "The code that was redeemed for this token. Deleting that code "
            "also withdraws this token."
        ),
    )
    token_hash = models.CharField(
        max_length=64,
        unique=True,
        editable=False,
        verbose_name=_("token hash"),
    )
    token_prefix = models.CharField(
        max_length=TOKEN_PREFIX_LENGTH,
        editable=False,
        verbose_name=_("token"),
        help_text=_(
            "The first characters of the token. The token itself is only "
            "known to the client it was handed to."
        ),
    )
    installation_id = models.CharField(
        max_length=255,
        blank=True,
        db_index=True,
        verbose_name=_("installation"),
    )
    revoked = models.BooleanField(
        default=False,
        verbose_name=_("revoked"),
        help_text=_("A revoked token cannot be used anymore."),
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_("created at"))
    last_used_at = models.DateTimeField(
        null=True,
        blank=True,
        editable=False,
        verbose_name=_("last used at"),
        help_text=_("Only updated once a day, so it can be off by up to one day."),
    )

    @classmethod
    def issue(
        cls, code: AreaCode, installation_id: str = ""
    ) -> tuple["AreaAccessToken", str]:
        """
        Create a token for the area of the given code.

        Registering again always adds a token and never revokes an existing
        one. Revoking the earlier token of the same installation would be
        tidier, but registration is unauthenticated and ``installation_id`` is
        whatever the client sent: anybody holding a code of the area — and
        codes are printed on flyers — could then knock a known installation
        offline, and two clients reporting the same id by accident would keep
        cutting each other off. A token that a reinstalled client left behind
        is withdrawn in the admin, or by deleting its code.

        :param code: The code that was redeemed
        :param installation_id: The installation of the client, if it sent one
        :return: The created token and its plaintext, which only exists here
        """
        token = generate_token()
        access_token = cls.objects.create(
            area=code.area,
            code=code,
            token_hash=hash_token(token),
            token_prefix=token[:TOKEN_PREFIX_LENGTH],
            installation_id=installation_id,
        )
        return access_token, token

    @classmethod
    def resolve(cls, token: str) -> "AreaAccessToken | None":
        """
        Look up the token a client sent.

        :param token: The token from the request
        :return: The matching token, or ``None`` if it is unknown or revoked
        """
        return (
            cls.objects.select_related("area")
            .filter(token_hash=hash_token(token), revoked=False)
            .first()
        )

    def touch(self) -> None:
        """
        Remember that the token was used, at most once a day.

        A client sends its token with every single request, so writing the
        timestamp each time would turn every read of the API into a write.

        The write goes through the queryset rather than through ``save()``:
        ``save(update_fields=...)`` raises if it hits no row, and the row can
        be gone between resolving the token and touching it, which would turn
        the ``401`` the client is owed into a ``500``.
        """
        timestamp = now()
        if self.last_used_at and timestamp - self.last_used_at < LAST_USED_RESOLUTION:
            return
        type(self).objects.filter(pk=self.pk).update(last_used_at=timestamp)
        self.last_used_at = timestamp

    def __str__(self) -> str:
        return f"{self.token_prefix}… ({self.area})"

    class Meta:
        """
        Meta class for the AreaAccessToken model.
        """

        verbose_name = _("Area access token")
        verbose_name_plural = _("Area access tokens")
        ordering = ["-created_at"]
