# Generated by Django 3.1b1 on 2020-07-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Lektion',
                'verbose_name_plural': 'Lektionen',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=255)),
                ('word2', models.CharField(max_length=255)),
                ('word3', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='images/')),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('training_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vocgui.trainingset')),
            ],
            options={
                'verbose_name': 'Wort',
                'verbose_name_plural': 'Wörter',
            },
        ),
    ]
