# Generated by Django 3.1.1 on 2020-11-02 16:19

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0006_auto_20200825_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.AlterModelOptions(
            name='trainingset',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.RenameField(
            model_name='trainingset',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='document',
            name='arcticle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='document',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='discipline',
            field=models.ManyToManyField(related_name="training_sets", to='vocgui.Discipline'),
            preserve_default=False,
        ),
    ]
