# Generated by Django 2.2.8 on 2020-09-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0006_auto_20200825_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
