# Generated by Django 3.1 on 2020-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0006_auto_20200825_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='arcticle',
            field=models.CharField(default='', max_length=255),
        ),
    ]
