# Generated by Django 3.1 on 2020-09-21 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0006_auto_20200825_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bereich',
                'verbose_name_plural': 'Bereiche',
            },
        ),
        migrations.AlterModelOptions(
            name='trainingset',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.RenameField(
            model_name='trainingset',
            old_name='description',
            new_name='details',
        ),
        migrations.AddField(
            model_name='trainingset',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_sets', to='vocgui.field'),
            preserve_default=False,
        ),
    ]
