# Generated by Django 3.1.1 on 2020-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0007_auto_20201102_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='arcticle',
        ),
        migrations.RemoveField(
            model_name='document',
            name='video_url',
        ),
        migrations.AddField(
            model_name='document',
            name='article',
            field=models.CharField(choices=[('der', 'der'), ('das', 'das'), ('die', 'die'), ('die (Plural)', 'die (Plural)')], default='', max_length=255),
        ),
    ]
