# Generated by Django 3.1.1 on 2020-09-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0007_auto_20200921_1302'),
        ('vocgui', '0007_document_arcticle'),
    ]

    operations = [
    ]
