# Generated by Django 3.1 on 2020-09-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0007_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingset',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
    ]
