# Generated by Django 3.1 on 2020-09-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0007_document_arcticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arcticle',
            field=models.CharField(default='', max_length=3),
        ),
    ]
