# Generated by Django 3.1 on 2020-09-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0008_auto_20200917_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingset',
            old_name='description',
            new_name='details',
        ),
    ]
