# Generated by Django 3.1.2 on 2020-10-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0009_auto_20200927_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='arcticle',
            new_name='article',
        ),
    ]
