# Generated by Django 3.1 on 2020-09-17 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0009_auto_20200917_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingset',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='training_sets', to='vocgui.field'),
            preserve_default=False,
        ),
    ]
