# Generated by Django 3.1.2 on 2020-10-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0010_auto_20201009_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='article',
            field=models.CharField(choices=[('der', 'der'), ('das', 'das'), ('die', 'die'), ('die (Plural)', 'die (Plural)')], default='', max_length=255),
        ),
    ]
