# Generated by Django 3.2rc1 on 2021-03-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0011_trainingset_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingset',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sets', to='vocgui.discipline', verbose_name='Bereichen'),
        ),
    ]
