# Generated by Django 3.2rc1 on 2021-03-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0013_auto_20210325_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimage',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
    ]
