# Generated by Django 3.2rc1 on 2021-03-28 14:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0014_alter_documentimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
