# Generated by Django 3.2rc1 on 2021-04-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0015_alter_documentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
