# Generated by Django 3.2.2 on 2021-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0017_auto_20210513_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingset',
            name='released',
            field=models.BooleanField(default=False),
        ),
    ]
