# Generated by Django 3.2.2 on 2021-05-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0018_auto_20210519_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='released',
            field=models.BooleanField(default=False, verbose_name='released'),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='released',
            field=models.BooleanField(default=False, verbose_name='released'),
        ),
    ]
