# Generated by Django 3.2.2 on 2021-06-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0021_auto_20210609_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creator_is_admin',
            field=models.BooleanField(default=True, verbose_name='admin'),
        ),
    ]
