# Generated by Django 3.2.2 on 2021-06-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0022_auto_20210528_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='created by'),
        ),
    ]
