# Generated by Django 3.2.3 on 2021-06-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0021_auto_20210611_0641'),
        ('vocgui', '0022_auto_20210612_0843'),
    ]

    operations = [
    ]
