# Generated by Django 3.2.2 on 2021-06-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('vocgui', '0023_auto_20210601_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='trainingset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='created by'),
        ),
    ]
