# Generated by Django 3.2.3 on 2021-06-22 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocgui', '0025_documentimage_confirmed'),
        ('vocgui', '0026_auto_20210621_1616'),
    ]

    operations = [
    ]
